# Generated by Django 4.2.1 on 2023-06-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
