# Generated by Django 4.2.1 on 2023-06-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comentario_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='signature',
            field=models.CharField(default='Firma', max_length=100),
        ),
    ]
