# Generated by Django 4.2.1 on 2023-06-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_coment_delete_comentario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comentarios',
        ),
    ]
