# Generated by Django 4.2.1 on 2023-06-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0005_rename_coment_comentarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comentario',
        ),
    ]
